### ISSUE TITLE
SyntaxError: Error parsing package.json: Unexpected token ] in JSON at position 271

### ISSUE THREAD

**Issue by blackthroat** [sheyabernstein/MMM-pihole-stats#11]
Upgraded MagicMirror from v2.14.0 to v2.15.0 and MM loads to black screen. Worked fine prior to upgrade.

Confirmed I was able to access `apiURL` from my browser without issue.

Commented out `MMM-pihole-stats` section from my `config.js` file and MM loads without issue.

Here are the logs:

```
/home/pi/.pm2/logs/mm-out.log last 15 lines:
0|mm       |
0|mm       | > magicmirror@2.15.0 start /home/pi/MagicMirror
0|mm       | > DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js
0|mm       |
0|mm       | [21.04.2021 18:56.13.383] [LOG]   Starting MagicMirror: v2.15.0
0|mm       | [21.04.2021 18:56.13.402] [LOG]   Loading config ...
0|mm       | [21.04.2021 18:56.13.430] [LOG]   Loading module helpers ...
0|mm       | [21.04.2021 18:56.13.645] [LOG]   Initializing new module helper ...
0|mm       | [21.04.2021 18:56.13.651] [LOG]   Module helper loaded: MMM-ModuleScheduler
0|mm       | [21.04.2021 18:56.13.661] [LOG]   No helper found for module: alert.
0|mm       | [21.04.2021 18:56.14.191] [LOG]   Initializing new module helper ...
0|mm       | [21.04.2021 18:56.14.195] [LOG]   Module helper loaded: updatenotification
0|mm       | [21.04.2021 18:56.14.197] [LOG]   No helper found for module: clock.
0|mm       | [21.04.2021 18:56.15.902] [LOG]   Initializing new module helper ...
0|mm       | [21.04.2021 18:56.15.905] [LOG]   Module helper loaded: calendar

0|mm  | [21.04.2021 18:56.20.556] [LOG]
0|mm  | Initializing new module helper ...
0|mm  | [21.04.2021 18:56.20.561] [LOG]   Module helper loaded: MMM-GoogleTasks
0|mm  | [21.04.2021 18:56.21.366] [LOG]
0|mm  | Initializing new module helper ...
0|mm  | [21.04.2021 18:56.21.368] [LOG]   Module helper loaded: MMM-Screencast
0|mm  | [21.04.2021 18:56.21.379] [LOG]
0|mm  | Initializing new module helper ...
0|mm  | [21.04.2021 18:56.21.381] [LOG]   Module helper loaded: currentweather
0|mm  | [21.04.2021 18:56.21.388] [LOG]   No helper found for module: MMM-AirQuality.
0|mm  | [21.04.2021 18:56.21.399] [LOG]
0|mm  | Initializing new module helper ...
0|mm  | [21.04.2021 18:56.21.400] [LOG]   Module helper loaded: weatherforecast
0|mm  | [21.04.2021 18:56.22.904] [LOG]
0|mm  | Initializing new module helper ...
0|mm  | [21.04.2021 18:56.22.906] [LOG]   Module helper loaded: MMM-Roomba
0|mm  | [21.04.2021 18:56.22.921] [ERROR]
0|mm  | WARNING! Could not validate config file. Starting with default configuration. Please correct syntax errors at or above this line: SyntaxError: Error parsing /home/pi/MagicMirror/modules/MMM-pihole-stats/package.json: Unexpected token ] in JSON at position 271
0|mm  |     at parse (<anonymous>)
0|mm  |     at readPackage (internal/modules/cjs/loader.js:269:20)
0|mm  |     at readPackageScope (internal/modules/cjs/loader.js:294:19)
0|mm  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:17)
0|mm  |     at Module.load (internal/modules/cjs/loader.js:992:32)
0|mm  |     at Module._load (internal/modules/cjs/loader.js:885:14)
0|mm  |     at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
0|mm  |     at Module.require (internal/modules/cjs/loader.js:1032:19)
0|mm  |     at require (internal/modules/cjs/helpers.js:72:18)
0|mm  |     at loadModule (/home/pi/MagicMirror/js/app.js:126:19)
0|mm  |     at loadNextModule (/home/pi/MagicMirror/js/app.js:164:5)
0|mm  |     at /home/pi/MagicMirror/js/app.js:166:6
0|mm  |     at Class.loaded (/home/pi/MagicMirror/js/node_helper.js:18:3)
0|mm  |     at loadModule (/home/pi/MagicMirror/js/app.js:143:6)
0|mm  |     at loadNextModule (/home/pi/MagicMirror/js/app.js:164:5)
0|mm  |     at /home/pi/MagicMirror/js/app.js:166:6
0|mm  |     at Class.loaded (/home/pi/MagicMirror/js/node_helper.js:18:3)
0|mm  |     at loadModule (/home/pi/MagicMirror/js/app.js:143:6)
0|mm  |     at loadNextModule (/home/pi/MagicMirror/js/app.js:164:5)
0|mm  |     at /home/pi/MagicMirror/js/app.js:166:6
0|mm  |     at loadModule (/home/pi/MagicMirror/js/app.js:145:4)
0|mm  |     at loadNextModule (/home/pi/MagicMirror/js/app.js:164:5)
0|mm  | [21.04.2021 18:56.22.926] [LOG]   Loading module helpers ...
0|mm  | [21.04.2021 18:56.22.930] [LOG]   Initializing new module helper ...
0|mm  | [21.04.2021 18:56.22.931] [LOG]   Module helper loaded: MMM-ModuleScheduler
0|mm  | [21.04.2021 18:56.22.934] [LOG]   No helper found for module: alert.
0|mm  | [21.04.2021 18:56.22.937] [LOG]   Initializing new module helper ...
0|mm  | [21.04.2021 18:56.22.940] [LOG]
0|mm  | Module helper loaded: updatenotification
0|mm  | [21.04.2021 18:56.22.947] [LOG]   No helper found for module: clock.
0|mm  | [21.04.2021 18:56.22.954] [LOG]   Initializing new module helper ...
0|mm  | [21.04.2021 18:56.22.959] [LOG]   Module helper loaded: calendar
0|mm  | [21.04.2021 18:56.22.963] [LOG]   Initializing new module helper ...
0|mm  | [21.04.2021 18:56.22.965] [LOG]
0|mm  | Module helper loaded: MMM-GoogleTasks
0|mm  | [21.04.2021 18:56.22.967] [LOG]   Initializing new module helper ...
0|mm  | [21.04.2021 18:56.22.968] [LOG]   Module helper loaded: MMM-Screencast
0|mm  | [21.04.2021 18:56.22.971] [LOG]   Initializing new module helper ...
0|mm  | [21.04.2021 18:56.22.976] [LOG]   Module helper loaded: currentweather
0|mm  | [21.04.2021 18:56.22.985] [LOG]   No helper found for module: MMM-AirQuality.
0|mm  | [21.04.2021 18:56.22.991] [LOG]   Initializing new module helper ...
0|mm  | [21.04.2021 18:56.22.996] [LOG]   Module helper loaded: weatherforecast
0|mm  | [21.04.2021 18:56.22.998] [LOG]   Initializing new module helper ...
0|mm  | [21.04.2021 18:56.23.000] [LOG]   Module helper loaded: MMM-Roomba
0|mm  | [21.04.2021 18:56.23.004] [ERROR] App threw an error during load
0|mm  | [21.04.2021 18:56.23.011] [ERROR] SyntaxError: Error parsing /home/pi/MagicMirror/modules/MMM-pihole-stats/package.json: Unexpected token ] in JSON at position 271
0|mm  |     at parse (<anonymous>)
0|mm  |     at readPackage (internal/modules/cjs/loader.js:269:20)
0|mm  |     at readPackageScope (internal/modules/cjs/loader.js:294:19)
0|mm  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:17)
0|mm  |     at Module.load (internal/modules/cjs/loader.js:992:32)
0|mm  |     at Module._load (internal/modules/cjs/loader.js:885:14)
0|mm  |     at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
0|mm  |     at Module.require (internal/modules/cjs/loader.js:1032:19)
0|mm  |     at require (internal/modules/cjs/helpers.js:72:18)
0|mm  |     at loadModule (/home/pi/MagicMirror/js/app.js:126:19)
0|mm  |     at loadNextModule (/home/pi/MagicMirror/js/app.js:164:5)
0|mm  |     at /home/pi/MagicMirror/js/app.js:166:6
0|mm  |     at Class.loaded (/home/pi/MagicMirror/js/node_helper.js:18:3)
0|mm  |     at loadModule (/home/pi/MagicMirror/js/app.js:143:6)
0|mm  |     at loadNextModule (/home/pi/MagicMirror/js/app.js:164:5)
0|mm  |     at /home/pi/MagicMirror/js/app.js:166:6
0|mm  |     at Class.loaded (/home/pi/MagicMirror/js/node_helper.js:18:3)
0|mm  |     at loadModule (/home/pi/MagicMirror/js/app.js:143:6)
0|mm  |     at loadNextModule (/home/pi/MagicMirror/js/app.js:164:5)
0|mm  |     at /home/pi/MagicMirror/js/app.js:166:6
0|mm  |     at loadModule (/home/pi/MagicMirror/js/app.js:145:4)
0|mm  |     at loadNextModule (/home/pi/MagicMirror/js/app.js:164:5)
0|mm  | [21.04.2021 18:56.23.021] [ERROR]
0|mm  | Whoops! There was an uncaught exception...
0|mm  | [21.04.2021 18:56.23.043] [ERROR]
0|mm  | SyntaxError: Error parsing /home/pi/MagicMirror/modules/MMM-pihole-stats/package.json: Unexpected token ] in JSON at position 271
0|mm  |     at parse (<anonymous>)
0|mm  |     at readPackage (internal/modules/cjs/loader.js:269:20)
0|mm  |     at readPackageScope (internal/modules/cjs/loader.js:294:19)
0|mm  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:17)
0|mm  |     at Module.load (internal/modules/cjs/loader.js:992:32)
0|mm  |     at Module._load (internal/modules/cjs/loader.js:885:14)
0|mm  |     at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
0|mm  |     at Module.require (internal/modules/cjs/loader.js:1032:19)
0|mm  |     at require (internal/modules/cjs/helpers.js:72:18)
0|mm  |     at loadModule (/home/pi/MagicMirror/js/app.js:126:19)
0|mm  |     at loadNextModule (/home/pi/MagicMirror/js/app.js:164:5)
0|mm  |     at /home/pi/MagicMirror/js/app.js:166:6
0|mm  |     at Class.loaded (/home/pi/MagicMirror/js/node_helper.js:18:3)
0|mm  |     at loadModule (/home/pi/MagicMirror/js/app.js:143:6)
0|mm  |     at loadNextModule (/home/pi/MagicMirror/js/app.js:164:5)
0|mm  |     at /home/pi/MagicMirror/js/app.js:166:6
0|mm  |     at Class.loaded (/home/pi/MagicMirror/js/node_helper.js:18:3)
0|mm  |     at loadModule (/home/pi/MagicMirror/js/app.js:143:6)
0|mm  |     at loadNextModule (/home/pi/MagicMirror/js/app.js:164:5)
0|mm  |     at /home/pi/MagicMirror/js/app.js:166:6
0|mm  |     at loadModule (/home/pi/MagicMirror/js/app.js:145:4)
0|mm  |     at loadNextModule (/home/pi/MagicMirror/js/app.js:164:5) {
0|mm  |   path: '/home/pi/MagicMirror/modules/MMM-pihole-stats/package.json'
0|mm  | }
0|mm  | [21.04.2021 18:56.23.052] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm  | [21.04.2021 18:56.23.057] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|mm  | [21.04.2021 18:56.23.581] [LOG]
0|mm  | Launching application.
```

Please let me know if you need anything else. Thanks!

**Comment by fourdotone12** [comment]
Me too. Same error.

**Comment by swooningfish** [comment]
Found deleting the package.json file resolved the issue

**Comment by blackthroat** [comment]
That did the trick for me too. Thanks @swooningfish

**Comment by swooningfish** [comment]
@sheyabernstein is it possible to remove it from the repo so future users don't experience the issue? I can setup a PR if required.

**Comment by sheyabernstein** [comment]
@swooningfish I'll merge the PR
