### ISSUE TITLE
Installed Bullseye -MMM-pihole-stats does not seem to work

### ISSUE THREAD

**Issue by bert269** [sheyabernstein/MMM-pihole-stats#16]
Hi

I installed Bullseye and I cannot seem to get MMM-pihole-stats to work. No to be truthfully it has been a while since I loaded this module, so I cannot say when it last worked.
node.js is at level 17.1
Magic Mirror2 as 2.17.1
This is the result from the pm2 log file:
/home/pi/.pm2/logs/mm-error.log last 15 lines:
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-pihole-stats/node_helper.js:2:15)
0|mm       |     at Module._compile (internal/modules/cjs/loader.js:1078:30)
0|mm       |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10) {
0|mm       |   code: 'MODULE_NOT_FOUND',
0|mm       |   requireStack: [
0|mm       |     '/home/pi/MagicMirror/modules/MMM-pihole-stats/node_helper.js',
0|mm       |     '/home/pi/MagicMirror/js/app.js',
0|mm       |     '/home/pi/MagicMirror/js/electron.js',
0|mm       |     '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
0|mm       |     undefined
0|mm       |   ]
0|mm       | }
This is my config entry:
{
            module: "MMM-pihole-stats",
            position: "top_right",
            config: {
                apitoken: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                showSources: "true",
                sourcesCount: "10",
                showSourceHostnameOnly: "true",
                updateInterval: "10000"      //in ms
           }
        },

Can you give me any guidance, please?
Thanks

**Comment by bert269** [comment]
Found the problem - this was the solution:
https://forum.magicmirror.builders/topic/15778/fix-for-black-screen-in-2-16-and-later
